feat: Add discord icon in header and footer
electron/electronjs.org pull request #4601
Opened 2020-10-04 23:00 UTC by parasg1999

I have used SVG for discord logo to achieve the same animations as the github and twitter icons in header/footer. Since I had to add new class for managing the svg fill color, there may be changes required in the file where I have to place the appropriate classes.

Suggestions are welcome. Posting screenshots as well (the animations are working, if you want I can post the GIF as well).

At header
![Screenshot from 2020-10-05 04-25-46](https://user-images.githubusercontent.com/31986918/95029046-f2b06280-06c2-11eb-882a-3240de94cc74.png)

At footer
![Screenshot from 2020-10-05 04-26-11](https://user-images.githubusercontent.com/31986918/95029049-f5ab5300-06c2-11eb-999e-a234ce09dbc4.png)

2020-10-05 20:20 UTC, erickzhao requested changes
Seems like when I set up style linting, I didn't account for any files that weren't directly in `public/styles`. I'll have to set up a PR to fix that.

Also: seems like the icon is misaligned in the navbar on Chrome/FF/Safari on macOS ![image](https://user-images.githubusercontent.com/16010076/95115526-7cc7ed80-06fa-11eb-897e-1ed4f8a5ad37.png).

2020-10-06 03:06 UTC, parasg1999 commented
I don't know what's causing the issue and since I don't have access to MacOS, could you help me in fixing the bug?

2020-10-06 17:32 UTC, erickzhao commented
Ref https://github.com/electron/electronjs.org/pull/4609 for aforementioned linter changes.

2020-10-06 18:57 UTC, vhashimotoo requested changes

2020-10-06 18:57 UTC, vhashimotoo commented on views/partials/footer.hbs
> +                  fill="#f6f8f8" id="logo" /></svg>
Can you please move this code to own reusable file like `partials/icons/discord.hbs`, and reuse them by `{{> icons/discord}}`

2020-10-06 18:57 UTC, vhashimotoo commented on views/partials/header.hbs
> +                  fill="#2f3241" id="logo" /></svg>
The same here

2020-10-06 19:14 UTC, parasg1999 commented
@vhashimotoo Made the required changes, please check.

2020-10-07 18:14 UTC, erickzhao requested changes
Figured out the alignment issue, and a color issue in the footer. @parasg1999 could you test these fixes locally to see if they work for you as well?

2020-10-07 18:14 UTC, erickzhao commented on views/partials/footer.hbs
> +          <li><a class="footer-social-icon vertical-middle" href="https://discord.gg/H6uTh7m"
```suggestion
          <li><a class="footer-social-icon vertical-middle" href="https://discord.gg/electron"
```

We got a vanity URL now :)

2020-10-07 18:14 UTC, erickzhao commented on public/styles/helpers/_icons.scss
> +      color: $main-color-strong;
```suggestion
      fill: $main-color-strong;
```

Renders as black using the `color` prop.

2020-10-07 18:42 UTC, parasg1999 commented
@erickzhao The fix actually moved the discord icon above the github icon, but removing the octicon class worked for me, could you check if these changes work for MacOS?

2020-10-07 21:49 UTC, erickzhao requested changes
The fix indeed worked for me. :) 

![screencast 2020-10-07 13-59-56](https://user-images.githubusercontent.com/16010076/95391573-213d6180-08ac-11eb-81cf-61e45d61c424.gif)

This is a direction in the right step, but the `.site-header-nav-item` class is leaving leftover hover styling.

https://github.com/electron/electronjs.org/blob/b0039fb951123cc1b2c24e81e8013f84d220185a/public/styles/helpers/_navigation.scss#L98-L99

I think we might want to clean this up by creating a separate `site-header-icon` class with similar styles to `.site-header-nav-item` minus the hover animation.

2020-10-08 08:39 UTC, parasg1999 commented
I added `site-header-nav-icon` class to the icon and used the scss rule for removing the hover.
Visually it still looks like the icon is above that of github but by using a [chrome extension](https://chrome.google.com/webstore/detail/baseliner/agoopbiflnjadjfbhimhlmcbgmdgldld/related?hl=en-GB) I was able to verify that they are aligned. I guess this is due to the circle not being complete in the github icon.

2022-03-30 17:18 UTC, closed without merging