docs: add copy button to spectrum and devotion code blocks
electron/electronjs.org pull request #4618
Opened 2020-10-08 23:58 UTC by stevejoachim

See #4617 

<img width="941" alt="image" src="https://user-images.githubusercontent.com/19378484/95524902-a0ac5d00-09a0-11eb-875b-1dac68fc58c4.png">

2020-10-09 18:23 UTC, erickzhao reviewed
![screencast 2020-10-09 11-13-57](https://user-images.githubusercontent.com/16010076/95618275-967e7300-0a21-11eb-9eff-7032b203f3ba.gif)

Getting a weird visual bug on Chrome and FF on macOS (not Safari). 🤔

2020-10-09 21:48 UTC, stevejoachim commented
Thanks for catching this! I was able to reproduce this on Firefox. It looks like the Copy button is trying to display a tooltip, but it gets trapped inside the code box and overflows it. I changed some CSS properties for the `pre` and `code` tags to fix this so that the tooltip will display (overflow: visible), but the actual code will still be scrollable (overflow: auto) if the window gets very narrow.

2020-10-13 20:44 UTC, erickzhao requested changes
![image](https://user-images.githubusercontent.com/16010076/95914132-242bcc80-0d5a-11eb-9bad-074cac523f58.png)

Seems like it's gotten visually weirder with the latest push 🤔

2020-10-13 21:02 UTC, stevejoachim commented
Thanks for reviewing. That's unfortunate that it's still messed up. What's your test setup? I can't reproduce that visual on Firefox, Safari, or Chrome on MacOS. This is what it's looking like in Firefox for me when hovering on one of the copy buttons:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/19378484/95914986-872a5d00-0d74-11eb-97a2-f008c0903242.png">

2020-10-13 21:48 UTC, vhashimotoo commented on public/styles/helpers/_code.scss
> +    overflow: visible;
```suggestion
	position: relative;
    overflow: visible;
```

2020-10-13 21:48 UTC, vhashimotoo commented on public/styles/helpers/_code.scss
> +      display: block;
```suggestion
      display: inline;
```

2020-10-13 21:52 UTC, vhashimotoo requested changes
I'm also able to repro the same behavior as @erickzhao on Chrome, Windows 10. The suggestions change behavior to the same as we have at the `/docs` page.

2020-10-13 21:52 UTC, vhashimotoo commented on public/styles/helpers/_code.scss
> +      overflow: scroll;
```suggestion
      overflow: initial;
```

2020-10-14 00:30 UTC, stevejoachim commented
@vhashimotoo Thanks for reviewing the code in such detail. I just made the changes you suggested.

2021-11-16 23:00 UTC, closed without merging